### ISSUE TITLE
Can you explain in some more detail about Custom Entitlements and why you needed to add Entitlements.plist

### ISSUE THREAD

**Issue by rs-memosoft** [LetsCreateSeries/TimeTrackerTutorial#3]
You mention this quite quickly in the videos and I don't understand why it's needed and what it does. Could you help by explaining in a bit more detail.  Thank you

**Comment by LetsCreateSeries** [comment]
Would you be interested in joining the Facebook group and posting questions there? 
https://www.facebook.com/groups/letscreateseries
